### ISSUE TITLE
MTLS connectivity between bridge and MQ server

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#171]
As of now, we are providing plain username/password in yaml config file for establishing connectivity between nats-mq bridge and MQ server unlike connection settings between nats-server and bridge where we are using TLS for authentication. Using plain username/password will create security issues hence need to have TLS support for this connectivity as well.

**Comment by gstaware** [comment]
Please also add few examples once this is implemented.

**Comment by RichardHightower** [comment]
Hi Rick,

              

To enable MTLS with the embedded MQ client we’ll need to be able to assign the location of the keystore/truststore combo using the System.SetProperty (#3 here..)

 

https://www.ibm.com/developerworks/websphere/library/techarticles/0510_fehners/0510_fehners.html

 

and then specify the ciphersuite which is #4 in the link.  The previous steps can be ignored.

 

Let me know if you run into any issues and I can help out.

 

Thanks,

**Comment by RichardHightower** [comment]
I believe the issue is MTLS vs TLS

**Comment by RichardHightower** [comment]
We do not have an IBM MQ server set up to test this. Please provide a sample Docker container based on IBM MQ to demonstrate how to configure JSSL on the IBM MQ side and provide keystone and truststores that work with this docker container. In the meantime, we have a workaround to continue testing. 

See:
https://github.com/nats-io/nats-jms-mq-bridge/issues/182

This should keep the ball moving with your existing IBM set up. 

Please look at it and advise.

**Comment by gstaware** [comment]
This is working fine now
