### ISSUE TITLE
Instead of printing whole message in logs, simply a mapping of nats subject to mq series queue should be enough

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#176]
Instead of printing whole message in logs, simply a printing a mapping of nats subject to mq series queue should be enough. If we keep on printing whole message, logs will keep on filling rapidly. If any concerns/thoughts, please put in a comment and we can discuss more.

**Comment by RichardHightower** [comment]
This is a trace mode operation. Turning off trace gets rid of whole message. You would not use this in production. You would only use this feature to debug a dev or integration server. This is probably ok for Trace. Please advise.

**Comment by RichardHightower** [comment]
The solution is to turn it off for production.

**Comment by gstaware** [comment]
I am okay with printing message in trace mode and stopping that in production. Can we also print mapping of nats-server subject and mq queue in logs? Like message is coming from mq queue DEV.QUEUE.1 and will be mapped to subject subject1 As of now, we are simply printing whole message like below

2020-07-02 06:41:49.680 TRACE 2979210 --- [Pool-1-worker-1] runtime                                  : The bridge-natstoibmmq bridge received message with body ��sr3com.mastercard.scss.nats.sample.model.SampleMessageJ    messageIDJtimeL

Like below
[TRC] NATS:tick to Queue:DEV.QUEUE.1 and message received is ....

Please let me know if this clarifies.

**Comment by gstaware** [comment]
Since we are already tracking this issue under #199 , closing this duplicate issue.
