### ISSUE TITLE
Monitoring for bridge.

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#180]
Please let us know if we can have http monitoring endpoint on some port(configurable in yaml config file) using which we can monitor in/out bytes/messages same like how we have for core nats server. Monitoring is going to be one of the most important activity once bridge is deployed in production so if we can have this it would be great.

**Comment by RichardHightower** [comment]
This exists and is documented. Please advise.

**Comment by RichardHightower** [comment]
Reviewed docs and it is tied to the admin bash script. We should add more docs on what that does and on promethues end point.
