### ISSUE TITLE
Bridge dependencies (shade, fat jar)

### ISSUE THREAD

**Issue by RichardHightower** [nats-io/nats-jms-mq-bridge#226]
Good morning, We have been trying to build the wrapper application by using the Kotlin sources and the dependencies. But building with Maven is giving a lot of trouble.

Can you please let us know if you have any alternative Java code in place of Kotlin? We are able to package the sources using “mvn package” command but we are not able to run the application using the newly created jar file, I am attaching the error your reference. We appreciate your help.

```
java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.	
at org.springframework.util.Assert.notEmpty(Assert.java:467)	
at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180)	
at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123)	
at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434)
```

**Comment by RichardHightower** [comment]
The issue does not seem to be a Kotlin issue. 

java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.	at org.springframework.util.Assert.notEmpty(Assert.java:467)	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180)	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123)	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434)
The issue seems to be an issue with the fat jar/shade maven plugin that you are using. 
If you post your pom.xml file. We can take a look.

**Comment by gstaware** [comment]
This has been resolved so we can close this issue. There was minor mistake which got fixed.
