### ISSUE TITLE
CCDT fix now reconnect not working

### ISSUE THREAD

**Issue by RichardHightower** [nats-io/nats-jms-mq-bridge#233]
____

We tried with json ccdt file and bridge is starting successfully. However, it behaves exactly same when we configured connectionnamelist in nats-bridge.yaml config file which means failover is NOT happening once we stop the queue manager to which bridge process gets connected initially. The queue managers configured in CCDT file are independent queue managers(and not the multi instance queue managers). Below are the properties configured under mq cluster. Also attaching CCDT.json file with this email which is used in this example. Please let me know your thoughts on this one.

 

nats.ibm.mq.queueManager: "*ganesh"

nats.ibm.mq.ccdtUrl: "file:/home/dc-user/ccdttabfiles/CCDT.json"

io.nats.ibm.mq.jms.prop.string.CLIENTRECONNECTOPTIONS: "ANY"

io.nats.ibm.mq.jms.prop.int.CLIENTRECONNECTTIMEOUT: 2

**Comment by RichardHightower** [comment]
`A quick fix might be to add the MQCNO_RECONNECT option on the MQCONN call.` --- Paul

**Comment by RichardHightower** [comment]
We were not able to reproduce this. It works for us. Wih and with/out MQCNO_RECONNECT equiv

**Comment by gstaware** [comment]
We verified and it works fine. Issue was with the way we were stopping the queue manager. It should be stopped with endmqm -r <QM> instead of endmqm <QM>. We can close this defect now.
